version: '3.8'

services:
  # Redis pour cache des modèles
  redis:
    image: redis:7-alpine
    container_name: luxury-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - luxury-network

  # Backend FastAPI
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: luxury-backend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEVICE=cpu
      - LOG_LEVEL=INFO
    volumes:
      - ../models:/app/models
      - ../backend/app:/app/app
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - luxury-network
    restart: unless-stopped

  # Frontend React
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: luxury-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - luxury-network
    restart: unless-stopped

  # Streamlit MVP
  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit
    container_name: luxury-streamlit
    ports:
      - "8501:8501"
    environment:
      - DEVICE=cpu
    volumes:
      - ../models:/app/models
      - ../streamlit_app:/app/streamlit_app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - luxury-network
    restart: unless-stopped

volumes:
  redis-data:
    driver: local

networks:
  luxury-network:
    driver: bridge
